services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: guard
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  app:
    build: .
    container_name: guardbot
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/guard
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
      -

  backup:
    image: postgres:latedst
    profiles: [ "backup" ]
    depends_on:
      - postgres
    volumes:
      - ./backups:/backups
    command: >
      sh -c "
        apk add --no-cache cron &&
        echo '0 0 * * * PGPASSWORD=postgres pg_dump -h postgres -U postgres -Fc guard > /backups/guard_\$(date +%%Y%%m%%d).dump' > /etc/crontabs/backup &&
        crontab /etc/crontabs/backup &&
        crond -f -l 2
      "

volumes:
  pgdata:
