spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/guard
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
botcommands:
  core:
    packages: org.makson.guardbot

