spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/guard
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yml
discord:
  token: ${DISCORD_TOKEN}
  guild-id: ${DISCORD_GUILD_ID}
  roles:
    core-protect:  ${DISCORD_CORE_PROTECT_ROLE}
    agent_guard:  ${DISCORD_AGENT_GUARD_ROLE}
  channels-id:
    special-report: ${DISCORD_SPECIAL_REPORT_CHANNEL_ID}
    log: ${DISCORD_LOG_CHANNEL_ID}
    guard-call: ${DISCORD_GUARD_CALL_CHANNEL_ID}
    report: ${DISCORD_REPORT_CHANNEL_ID}
botcommands:
  core:
    packages: org.makson.guardbot
  modals:
    enable: false
